### ISSUE TITLE
Issue: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app/com.shantanudeshmukh.linkedinsdk.LinkedInAuthenticationActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView

### ISSUE THREAD

**Issue by DevToDipesh** [shantanu-deshmukh/LinkedIn-SDK-Android#2]
FATAL EXCEPTION: Thread-1120
Process: com.socreates, PID: 18389
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app/com.shantanudeshmukh.linkedinsdk.LinkedInAuthenticationActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
	at android.app.ActivityThread.access$1200(ActivityThread.java:152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:40)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:68)
	at androidx.test.espresso.action.Tap.a(Tap.java)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:9)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.shantanudeshmukh.linkedinsdk.LinkedInAuthenticationActivity.onCreate(LinkedInAuthenticationActivity.java:58)
	at android.app.Activity.performCreate(Activity.java:6013)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:13)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
	... 24 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
	... 39 more
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x3040002
	at android.content.res.HwResources.getText(HwResources.java:1252)
	at android.content.res.Resources.getString(Resources.java:374)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:948)
	at com.android.org.chromium.con

**Comment by shantanu-deshmukh** [comment]
Hi @DevToDipesh, please provide more details about how to reproduce this issue. A example repo will help.

**Comment by NPatel1090** [comment]
@shantanu-deshmukh - I have integrated linkedin in my app but...

App got rejected from playstore for below reason.
Authentication via WebView

Your app performs authentication via WebViews, which leads to security and usability issues. Please see [this Google Help Center article](https://support.google.com/faqs/answer/12284343) for details.

com.shantanudeshmukh.linkedinsdk.LinkedInAuthenticationActivity.onCreate

**Comment by ThruThings** [comment]
@NPatel1090, we are experiencing the exact same issue with our app. Has anyone found a solution?

**Comment by shaikhemran79** [comment]
i am also facing the same issue in play store have you resolved it? please share if yes
